---

# derived from https://github.com/jcalazan/ansible-django-stack

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: tag_role_hypermap
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/ubuntu.yml

  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
