---

# Git settings.
setup_git_repo: yes
git_branch: master


# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: "{{ application_name }}"


# Nginx settings.
nginx_server_name: 192.168.33.15
ssl_src_dir: ssl_self_signed
ssl_dest_dir: /etc/ssl
ssl_key_password: password


# RabbitMQ settings.
rabbitmq_server_name: "{{ inventory_hostname }}"

rabbitmq_admin_user: admin
rabbitmq_admin_password: password

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password


# Celery settings.
celery_num_workers: 2
flower_admin_password: password


# Application settings.
django_settings_file: "settings.default"
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"

broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

run_django_db_migrations: yes
run_django_collectstatic: yes
