---
applications:
- name: hypermap
  domain: cfapps.io
  buildpack: https://github.com/panchicore/geonode-python-buildpack
  command: cf/init_db.sh
  instances: 1
  memory: 512M
  disk_quota: 2G
  services:
    - hypermap-database
    - hypermap-rabbitmq
    - hypermap-elasticsearch
    - hypermap-papertrail
  env:
    #TODO: Make an env variable on the CF side with a different key.
    # this one is exposed.
    SECRET_KEY: 'il%c@@m#*b@g%6s)!!pme9eog$j)!kq^7u8@3l(&)kprsi3$$x'
    DEBUG: 'True'
    DJANGO_SETTINGS_MODULE: 'hypermap.settings'
- name: hypermap-celery
  domain: cfapps.io
  buildpack: https://github.com/panchicore/geonode-python-buildpack
  command: cf/init_celery.sh
  health-check-type: none
  no-route: true
  instances: 1
  memory: 512M
  disk_quota: 2G
  services:
    - hypermap-database
    - hypermap-rabbitmq
    - hypermap-elasticsearch
    - hypermap-papertrail
  env:
    #TODO: Make an env variable on the CF side with a different key.
    # this one is exposed.
    SECRET_KEY: 'il%c@@m#*b@g%6s)!!pme9eog$j)!kq^7u8@3l(&)kprsi3$$x'
    DEBUG: 'True'
    DJANGO_SETTINGS_MODULE: 'hypermap.settings'
