---

- name: Install additional packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libjpeg-dev
    - python-imaging
    - vim
    - libgeos-dev
    - python-lxml
    - libgdal-dev
    - python-shapely
    - libproj0
