---

- include: install_additional_packages.yml
  tags: packages

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: setup_nginx.yml
  tags: nginx

- include: setup_uwsgi.yml
  tags: uwsgi

- include: set_file_permissions.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor
