---

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ uwsgi_user }}
        group={{ uwsgi_user }}
        state=directory
  notify: restart application
